-- ==============================================================
-- DB Cargo Belgium — Supabase Database Setup & Initial Seed
-- Voer dit eenmalig uit in de Supabase SQL Editor (https://supabase.com)
-- ==============================================================

-- 1. Maak de locations tabel aan
CREATE TABLE IF NOT EXISTS public.locations (
    id TEXT PRIMARY KEY,
    category TEXT DEFAULT 'bediening',
    name TEXT NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    aliases JSONB DEFAULT '[]'::jsonb,
    is_merged BOOLEAN DEFAULT FALSE,
    merged_into TEXT DEFAULT NULL,
    data JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Schakel Row Level Security (RLS) in en sta veilige anonieme toegang toe
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read" ON public.locations;
CREATE POLICY "Public Read" ON public.locations FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Insert" ON public.locations;
CREATE POLICY "Public Insert" ON public.locations FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Update" ON public.locations;
CREATE POLICY "Public Update" ON public.locations FOR UPDATE USING (true) WITH CHECK (true);

-- 3. Schakel Realtime in voor live synchronisatie tussen collega's
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'locations'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.locations;
    END IF;
END $$;

-- 4. Initial Seed van alle 39 bedieningen en 9 bundels
INSERT INTO public.locations (id, category, name, lat, lng, aliases, data) VALUES
  ('wal_can', 'bediening', 'Wallenius Canadakaai (CAST)', 51.315, 3.238, '["CAST", "Wallenius", "Canadakaai", "Kaai 107-108"]'::jsonb, '{"id": "wal_can", "name": "Wallenius Canadakaai (CAST)", "cluster": "zeebrugge", "zone": "PP-321", "zone_name": "Zeebrugge Zuidelijk Insteekdok", "has_bi": true, "bi_version": "V2.2", "type": "Automotive / RoRo Terminal", "moederbundel": "Bundel Ramskapelle", "sporen": "Spoor 843 (sporen 1 t.e.m. 4)", "adres": "Canadakaai (Kaai 107-108), 8380 Zeebrugge", "toegang_weg": "Barlenhuisstraat / Alfred Ronsestraat", "beveiliging": "Stuitklamp tussen poort en spoor 843, Siemensslot", "ppgi_ref": "PP-321 blz. 9, 21, 33", "lat": 51.315, "lng": 3.238, "aliases": ["CAST", "Wallenius", "Canadakaai", "Kaai 107-108"]}'::jsonb),
  ('cdmz', 'bediening', 'CDMZ (Car Delivery & Maintenance Zeebrugge)', 51.3115, 3.231, '["CDMZ Ramskapelle", "Car Delivery Zeebrugge"]'::jsonb, '{"id": "cdmz", "name": "CDMZ (Car Delivery & Maintenance Zeebrugge)", "cluster": "zeebrugge", "zone": "PP-321", "zone_name": "Zeebrugge Zuidelijk Insteekdok", "has_bi": true, "bi_version": "V1.2", "type": "Automotive Terminal", "moederbundel": "Bundel Ramskapelle", "sporen": "Spoor 898 (sporen 1 en 2, lengte 340m)", "adres": "Alfred Ronsestraat / Barlenhuisstraat (Kaai 101-102), 8380 Zeebrugge", "toegang_weg": "Alfred Ronsestraat", "beveiliging": "Stuitklamp 93R, OW met Andreaskruis", "ppgi_ref": "PP-321 blz. 9, 21", "lat": 51.3115, "lng": 3.231, "aliases": ["CDMZ Ramskapelle", "Car Delivery Zeebrugge"]}'::jsonb),
  ('cro_brit', 'bediening', 'C.RO Brittaniadok (SEA-RO)', 51.336296, 3.225474, '["SEA-RO", "Brittaniadok", "Kaai 701-704"]'::jsonb, '{"id": "cro_brit", "name": "C.RO Brittaniadok (SEA-RO)", "cluster": "zeebrugge", "zone": "PP-321", "zone_name": "Zeebrugge Zuidelijk Insteekdok", "has_bi": true, "bi_version": "V2.2", "type": "RoRo / Automotive Terminal", "moederbundel": "Bundel Ramskapelle", "sporen": "Spoor 872 (kaaien 701-704)", "adres": "Brittaniadok, 8380 Zeebrugge", "toegang_weg": "Isabellalaan / Barlenhuisstraat", "beveiliging": "Ontspoortong 10R, stuitklamp tussen poort en OW17, sleutel 321FR", "ppgi_ref": "PP-321 blz. 9, 22, 27", "lat": 51.336296, "lng": 3.225474, "aliases": ["SEA-RO", "Brittaniadok", "Kaai 701-704"]}'::jsonb),
  ('ico_toy', 'bediening', 'ICO Hanze Toyota', 51.301401, 3.244658, '["Hanze Terminal", "Toyota Zeebrugge"]'::jsonb, '{"id": "ico_toy", "name": "ICO Hanze Toyota", "cluster": "zeebrugge", "zone": "PP-321", "zone_name": "Zeebrugge Zuidelijk Insteekdok", "has_bi": true, "bi_version": "V2.0", "type": "Automotive Terminal", "moederbundel": "Bundel Ramskapelle", "sporen": "Spoor 879 (sporen 1 t.e.m. 3, ~325m)", "adres": "Hanzedok (Kaaien 501-504), 8380 Zeebrugge", "toegang_weg": "Lanceloot Blondeellaan", "beveiliging": "Stuitklamp met koppelslot, OW op terminal", "ppgi_ref": "PP-321 blz. 9, 21", "lat": 51.301401, "lng": 3.244658, "aliases": ["Hanze Terminal", "Toyota Zeebrugge"]}'::jsonb),
  ('ico1', 'bediening', 'Bastenakenkaai ICO 1', 51.306687, 3.217235, '["ICO Bastenaken 1", "Bastenakenkaai Kaai 500"]'::jsonb, '{"id": "ico1", "name": "Bastenakenkaai ICO 1", "cluster": "zeebrugge", "zone": "PP-321", "zone_name": "Zeebrugge Zuidelijk Insteekdok", "has_bi": true, "bi_version": "V1.5", "type": "Automotive / Multipurpose", "moederbundel": "Bundel Pelikaan", "sporen": "Sporen 21 t.e.m. 24 (kopsporen ~320m)", "adres": "Bastenakenkaai (Kaai 201-205), Margareta van Oostenrijkstraat, 8380 Zeebrugge", "toegang_weg": "Margareta van Oostenrijkstraat nabij OW21", "beveiliging": "Stuitklamp tussen OW21 en wissel 532, Siemenssleutels 442/443, Wilka G*", "ppgi_ref": "PP-321 blz. 9, 20, 27", "lat": 51.306687, "lng": 3.217235, "aliases": ["ICO Bastenaken 1", "Bastenakenkaai Kaai 500"]}'::jsonb),
  ('ico2', 'bediening', 'Bastenakenkaai ICO 2', 51.296014, 3.22717, '["ICO Bastenaken 2"]'::jsonb, '{"id": "ico2", "name": "Bastenakenkaai ICO 2", "cluster": "zeebrugge", "zone": "PP-321", "zone_name": "Zeebrugge Zuidelijk Insteekdok", "has_bi": true, "bi_version": "V1.2", "type": "Automotive / Multipurpose", "moederbundel": "Bundel Pelikaan", "sporen": "Sporen 31 t.e.m. 34", "adres": "Bastenakenkaai (Kaai 206-209), Margareta van Oostenrijkstraat, 8380 Zeebrugge", "toegang_weg": "Margareta van Oostenrijkstraat", "beveiliging": "Stuitklamp linker tak wissel 502, OW Margareta van Oostenrijkstraat", "ppgi_ref": "PP-321 blz. 9, 20, 27", "lat": 51.296014, "lng": 3.22717, "aliases": ["ICO Bastenaken 2"]}'::jsonb),
  ('efico', 'bediening', 'SA Efico (Koffieterminal)', 51.295931, 3.225249, '[]'::jsonb, '{"id": "efico", "name": "SA Efico (Koffieterminal)", "cluster": "zeebrugge", "zone": "PP-321", "zone_name": "Zeebrugge Zuidelijk Insteekdok", "has_bi": false, "bi_version": null, "type": "Commodities / Koffie Terminal", "moederbundel": "Bundel Pelikaan", "sporen": "Via spoor 871", "adres": "Margareta van Oostenrijkstraat 14, 8380 Zeebrugge", "toegang_weg": "Margareta van Oostenrijkstraat", "beveiliging": "Omheining, poort, stuitklamp linker tak wissel 551", "ppgi_ref": "PP-321 blz. 9, 22, 36-38", "lat": 51.295931, "lng": 3.225249, "aliases": []}'::jsonb),
  ('ndq', 'bediening', 'SA NDQ (NDQ Logistics)', 51.300855, 3.221456, '[]'::jsonb, '{"id": "ndq", "name": "SA NDQ (NDQ Logistics)", "cluster": "zeebrugge", "zone": "PP-321", "zone_name": "Zeebrugge Zuidelijk Insteekdok", "has_bi": false, "bi_version": null, "type": "Logistieke Terminal", "moederbundel": "Bundel Pelikaan", "sporen": "Via spoor 871", "adres": "Margareta van Oostenrijkstraat, 8380 Zeebrugge", "toegang_weg": "Margareta van Oostenrijkstraat", "beveiliging": "Stuitklamp 63R linker tak wissel 552, Siemensslot 244/115, Wilka G*", "ppgi_ref": "PP-321 blz. 9, 22, 39-41", "lat": 51.300855, "lng": 3.221456, "aliases": []}'::jsonb),
  ('spoorfuel', 'bediening', 'Spoorfuelinstallatie G&V', 51.3135, 3.227, '[]'::jsonb, '{"id": "spoorfuel", "name": "Spoorfuelinstallatie G&V", "cluster": "zeebrugge", "zone": "PP-321", "zone_name": "Zeebrugge Zuidelijk Insteekdok", "has_bi": false, "bi_version": null, "type": "Tractiebrandstof / Tankinstallatie", "moederbundel": "Bundel Ramskapelle", "sporen": "Doodspoor 899 (lengte 110m nuttig)", "adres": "Barlenhuisstraat (Bundel Ramskapelle), 8380 Zeebrugge", "toegang_weg": "Barlenhuisstraat", "beveiliging": "Ontspoortong 91AR, telefonische aanvraag Blok 7", "ppgi_ref": "PP-321 blz. 9, 21, 83-84", "lat": 51.3135, "lng": 3.227, "aliases": []}'::jsonb),
  ('ecs_bl', 'bediening', 'ECS 2XL Blauwe Loods', 51.314319, 3.191335, '["SA ECS2 Z", "SA ECS2 N", "ECS 2", "Blauwe Loods Zwankendamme"]'::jsonb, '{"id": "ecs_bl", "name": "ECS 2XL Blauwe Loods", "cluster": "zeebrugge", "zone": "PP-311", "zone_name": "Zeebrugge Noord / Voorhaven", "has_bi": true, "bi_version": "V3.1", "type": "Dry Cargo & Logistiek", "moederbundel": "Bundel Zwankendamme", "sporen": "Sporen 135 & 358 (SA ECS2 Z en ECS2 N)", "adres": "Wulfsberge / Lanceloot Blondeellaan, 8380 Zeebrugge (Zwankendamme)", "toegang_weg": "Wulfsberge", "beveiliging": "Ontspoortong 96G (Zuid) & elektrische stuitklamp 55H (Noord)", "ppgi_ref": "PP-311 blz. 10, 23, 43", "lat": 51.314319, "lng": 3.191335, "aliases": ["SA ECS2 Z", "SA ECS2 N", "ECS 2", "Blauwe Loods Zwankendamme"]}'::jsonb),
  ('2xl_bml', 'bediening', '2XL BML / SA ECS 1', 51.312115, 3.18893, '["SA ECS 1", "ECS 1", "Baron de Maerelaan 155"]'::jsonb, '{"id": "2xl_bml", "name": "2XL BML / SA ECS 1", "cluster": "zeebrugge", "zone": "PP-311", "zone_name": "Zeebrugge Noord / Voorhaven", "has_bi": true, "bi_version": "V1.5", "type": "Logistiek & Warehousing", "moederbundel": "Zeebrugge Vorming / Bundel A", "sporen": "Spoor 460 (loods) & Spoor 524 (omloopspoor)", "adres": "Baron de Maerelaan 155, 8380 Zeebrugge", "toegang_weg": "Baron de Maerelaan / Kustlaan", "beveiliging": "Ontspoortong 54BG, Seinen Q524-G.4 & W460-G.4", "ppgi_ref": "PP-311 blz. 9, 10, 23, 42, 49", "lat": 51.312115, "lng": 3.18893, "aliases": ["SA ECS 1", "ECS 1", "Baron de Maerelaan 155"]}'::jsonb),
  ('nid_ico', 'bediening', 'NID ICO Northern Inlet Terminal', 51.327903, 3.208609, '["NIT", "Northern Inlet Terminal", "NID Westeroever"]'::jsonb, '{"id": "nid_ico", "name": "NID ICO Northern Inlet Terminal", "cluster": "zeebrugge", "zone": "PP-311", "zone_name": "Zeebrugge Noord / Voorhaven", "has_bi": true, "bi_version": "V2.0", "type": "Automotive / RoRo Terminal", "moederbundel": "Terminal NID (Noordelijk Insteekdok)", "sporen": "Sporen 4 & 5 Westeroever Achterkaai", "adres": "Noordelijk Insteekdok (Kaaien 405-410), 8380 Zeebrugge", "toegang_weg": "Koffieweg / Lanceloot Blondeellaan", "beveiliging": "Ontspoortong, beweegbare brug, OW70", "ppgi_ref": "PP-311 blz. 9, 10", "lat": 51.327903, "lng": 3.208609, "aliases": ["NIT", "Northern Inlet Terminal", "NID Westeroever"]}'::jsonb),
  ('po_ferries', 'bediening', 'P&O Ferries (P&O 501 / Zuid)', 51.336832, 3.190455, '["P&O Westerhoofd", "P&O 501", "P&O Ferries Zeebrugge"]'::jsonb, '{"id": "po_ferries", "name": "P&O Ferries (P&O 501 / Zuid)", "cluster": "zeebrugge", "zone": "PP-311", "zone_name": "Zeebrugge Noord / Voorhaven", "has_bi": true, "bi_version": "V1.9", "type": "Ferry / RoRo Terminal", "moederbundel": "Voorhaven-West / CHZ", "sporen": "Spoor 501 (Westerhoofd)", "adres": "Doverlaan / Westerhoofd (Buitenhaven), 8380 Zeebrugge", "toegang_weg": "Doverlaan", "beveiliging": "Terminalpoort, schuifrangering met sein V-L.4", "ppgi_ref": "PP-311 blz. 10, 31", "lat": 51.336832, "lng": 3.190455, "aliases": ["P&O Westerhoofd", "P&O 501", "P&O Ferries Zeebrugge"]}'::jsonb),
  ('stora', 'bediening', 'Stora Enso (PSA Breakbulk)', 51.351281, 3.17713, '["PSA Breakbulk", "StoraEnso"]'::jsonb, '{"id": "stora", "name": "Stora Enso (PSA Breakbulk)", "cluster": "zeebrugge", "zone": "PP-311", "zone_name": "Zeebrugge Noord / Voorhaven", "has_bi": true, "bi_version": "V1.3", "type": "Papier & Bosbouw Logistiek", "moederbundel": "Voorhaven-West", "sporen": "Sporen 1 & 2 (via aansluitspoor 803)", "adres": "Caxtonweg (tussen Albert II-dok en Wielingendok), 8380 Zeebrugge", "toegang_weg": "Caxtonweg", "beveiliging": "Aansluitspoor 803, verplicht poort openen via PSA security", "ppgi_ref": "PP-311 blz. 10, 68", "lat": 51.351281, "lng": 3.17713, "aliases": ["PSA Breakbulk", "StoraEnso"]}'::jsonb),
  ('dartline', 'bediening', 'Herstelspoor Dartline', 51.350343, 3.170285, '["Herstelspoor Dartline", "Dartline Zeebrugge"]'::jsonb, '{"id": "dartline", "name": "Herstelspoor Dartline", "cluster": "zeebrugge", "zone": "PP-311", "zone_name": "Zeebrugge Noord / Voorhaven", "has_bi": true, "bi_version": "V1.1", "type": "Wagonherstelling & Spooronderhoud", "moederbundel": "Voorhaven-West", "sporen": "Sporen 1 t.e.m. 3 (operationeel 617m, 612m, 623m)", "adres": "Caxtonweg (naast Stora Enso), 8380 Zeebrugge", "toegang_weg": "Caxtonweg", "beveiliging": "OW Cat 3 (zelf sleutelen), spoor 804, wielkeggen", "ppgi_ref": "PP-311 blz. 10, 68", "lat": 51.350343, "lng": 3.170285, "aliases": ["Herstelspoor Dartline", "Dartline Zeebrugge"]}'::jsonb),
  ('cro_albert', 'bediening', 'C.Ro Ports Albert II Dok', 51.349, 3.188, '["SA CHZ Terminal", "CHZ", "Albert II Dok"]'::jsonb, '{"id": "cro_albert", "name": "C.Ro Ports Albert II Dok", "cluster": "zeebrugge", "zone": "PP-311", "zone_name": "Zeebrugge Noord / Voorhaven", "has_bi": true, "bi_version": "Draft V1.0", "type": "RoRo & Multipurpose Terminal", "moederbundel": "Bundel CHZ Terminal", "sporen": "Sporen 3 & 5 (CHZ)", "adres": "New Yorklaan / Albert II-dok, 8380 Zeebrugge", "toegang_weg": "New Yorklaan", "beveiliging": "Toegangspoort, konvooi splitsen t.h.v. OW", "ppgi_ref": "PP-311 blz. 9, 37-39", "lat": 51.349, "lng": 3.188, "aliases": ["SA CHZ Terminal", "CHZ", "Albert II Dok"]}'::jsonb),
  ('csp_term', 'bediening', 'SA CSP Terminal NV (Cosco)', 51.342194, 3.187923, '["Cosco Shipping Ports", "CSP Zeebrugge", "Containerterminal Zeebrugge"]'::jsonb, '{"id": "csp_term", "name": "SA CSP Terminal NV (Cosco)", "cluster": "zeebrugge", "zone": "PP-311", "zone_name": "Zeebrugge Noord / Voorhaven", "has_bi": false, "bi_version": null, "type": "Deepsea Container Terminal", "moederbundel": "Zeebrugge Kaai / Voorhaven", "sporen": "Via spoor 851", "adres": "New Yorklaan / Albert II-dok (Wielingendok), 8380 Zeebrugge", "toegang_weg": "New Yorklaan", "beveiliging": "Stuitklamp met sleutel 334, procedure via Blok 4", "ppgi_ref": "PP-311 blz. 10, 26, 35", "lat": 51.342194, "lng": 3.187923, "aliases": ["Cosco Shipping Ports", "CSP Zeebrugge", "Containerterminal Zeebrugge"]}'::jsonb),
  ('psa_zb', 'bediening', 'SA PSA Zeebrugge NV (Container)', 51.3538, 3.183675, '["PSA Zeebrugge Container"]'::jsonb, '{"id": "psa_zb", "name": "SA PSA Zeebrugge NV (Container)", "cluster": "zeebrugge", "zone": "PP-311", "zone_name": "Zeebrugge Noord / Voorhaven", "has_bi": false, "bi_version": null, "type": "Container Terminal", "moederbundel": "Voorhaven-West / Strand", "sporen": "Spoor 871", "adres": "Pieter Troostlaan (Kaai 871), 8380 Zeebrugge", "toegang_weg": "Pieter Troostlaan", "beveiliging": "Eigen stuitklamp SA PSA Zeebrugge NV", "ppgi_ref": "PP-311 blz. 10, 26, 40", "lat": 51.3538, "lng": 3.183675, "aliases": ["PSA Zeebrugge Container"]}'::jsonb),
  ('psa_hnn', 'bediening', 'SA PSA - HNN', 51.337, 3.1925, '["Hesse-Noord Natie", "PSA HNN 801"]'::jsonb, '{"id": "psa_hnn", "name": "SA PSA - HNN", "cluster": "zeebrugge", "zone": "PP-311", "zone_name": "Zeebrugge Noord / Voorhaven", "has_bi": false, "bi_version": null, "type": "Multipurpose Terminal", "moederbundel": "Voorhaven-West", "sporen": "Spoor 801", "adres": "Pieter Troostlaan (Kaai 801), 8380 Zeebrugge", "toegang_weg": "Pieter Troostlaan", "beveiliging": "Stuitklamp / poortbediening", "ppgi_ref": "PP-311 blz. 10, 31", "lat": 51.337, "lng": 3.1925, "aliases": ["Hesse-Noord Natie", "PSA HNN 801"]}'::jsonb),
  ('po_nsf', 'bediening', 'SA P&O - NSF (North Sea Ferries)', 51.355, 3.214, '["North Sea Ferries", "P&O NSF Spoor 851"]'::jsonb, '{"id": "po_nsf", "name": "SA P&O - NSF (North Sea Ferries)", "cluster": "zeebrugge", "zone": "PP-311", "zone_name": "Zeebrugge Noord / Voorhaven", "has_bi": false, "bi_version": null, "type": "Ferry Veerboot Terminal", "moederbundel": "Zeebrugge Kaai", "sporen": "Via spoor 851 (verbindingen Brugge & spoor 5-6 zee)", "adres": "Leopold II-dam (Kaai 851), 8380 Zeebrugge", "toegang_weg": "Leopold II-dam", "beveiliging": "Stuitklampen SA P&O NSF", "ppgi_ref": "PP-311 blz. 10, 26, 35", "lat": 51.355, "lng": 3.214, "aliases": ["North Sea Ferries", "P&O NSF Spoor 851"]}'::jsonb),
  ('zb_kaai', 'bediening', 'Zeebrugge Kaai (Infrabel)', 51.338374, 3.206785, '["Kaaispoor 851 Infrabel", "Zeebrugge-Kaai"]'::jsonb, '{"id": "zb_kaai", "name": "Zeebrugge Kaai (Infrabel)", "cluster": "zeebrugge", "zone": "PP-311", "zone_name": "Zeebrugge Noord / Voorhaven", "has_bi": false, "bi_version": null, "type": "Openbare Kades & Spoorlijn", "moederbundel": "Zeebrugge Kaai", "sporen": "Spoor 851", "adres": "Centrale havenkades spoor 851, 8380 Zeebrugge", "toegang_weg": "Kustlaan / Leopold II-dam", "beveiliging": "Kleine beweging onder Blok 4", "ppgi_ref": "PP-311 blz. 10, 26, 36", "lat": 51.338374, "lng": 3.206785, "aliases": ["Kaaispoor 851 Infrabel", "Zeebrugge-Kaai"]}'::jsonb),
  ('zweedse_kaai', 'bediening', 'Zweedse Kaai', 51.339031, 3.206935, '["Zweedse Kaai Zeebrugge"]'::jsonb, '{"id": "zweedse_kaai", "name": "Zweedse Kaai", "cluster": "zeebrugge", "zone": "PP-311", "zone_name": "Zeebrugge Noord / Voorhaven", "has_bi": false, "bi_version": null, "type": "Autoterminal / Historische Kades", "moederbundel": "Lijn 202 / Verbindingsdok", "sporen": "Kaaisporen Zweedse Kaai", "adres": "Zweedse Kaai / Verbindingsdok, 8380 Zeebrugge", "toegang_weg": "Kustlaan", "beveiliging": "Historische aansluiting L202", "ppgi_ref": "PP-311 blz. 1, 3", "lat": 51.339031, "lng": 3.206935, "aliases": ["Zweedse Kaai Zeebrugge"]}'::jsonb),
  ('proviron', 'bediening', 'SA Proviron (Chemicals)', 51.216279, 2.951696, '["Proviron Chemicals Oostende"]'::jsonb, '{"id": "proviron", "name": "SA Proviron (Chemicals)", "cluster": "oostende", "zone": "PP-341", "zone_name": "Oostende & Plassendale", "has_bi": false, "bi_version": null, "type": "Chemie / Tankwagens", "moederbundel": "Oostende Vorming", "sporen": "Spoor 151", "adres": "George Stephensonstraat / Karperstraat, 8400 Oostende", "toegang_weg": "Industriezone Plassendale 1", "beveiliging": "Telefoontoelating Blok 7, kleine beweging", "ppgi_ref": "PP-341 blz. 9, 31", "lat": 51.216279, "lng": 2.951696, "aliases": ["Proviron Chemicals Oostende"]}'::jsonb),
  ('tilbury', 'bediening', 'Tilbury (Goederenoverslag)', 51.229, 2.929, '["Tilbury Kaai Oostende", "Goederenoverslag Oostende"]'::jsonb, '{"id": "tilbury", "name": "Tilbury (Goederenoverslag)", "cluster": "oostende", "zone": "PP-341", "zone_name": "Oostende & Plassendale", "has_bi": false, "bi_version": null, "type": "Goederen / Bulk & Stukgoed", "moederbundel": "Handelsdok Oostende", "sporen": "Sporen 1 & 2 (via spoor 254)", "adres": "Vergunningenstraat / Sloepenstraat / Molendorpkaai, 8400 Oostende", "toegang_weg": "Benedenstuwbrug", "beveiliging": "Omheining, poort, bediening brug door De Vlaamse Waterweg, max 1 loc", "ppgi_ref": "PP-341 blz. 8, 28, 31-32", "lat": 51.229, "lng": 2.929, "aliases": ["Tilbury Kaai Oostende", "Goederenoverslag Oostende"]}'::jsonb),
  ('plassendale', 'bediening', 'Bundel Plassendale 1', 51.211, 2.998, '["Plassendale 1", "Industrieterrein Plassendale"]'::jsonb, '{"id": "plassendale", "name": "Bundel Plassendale 1", "cluster": "oostende", "zone": "PP-341", "zone_name": "Oostende & Plassendale", "has_bi": false, "bi_version": null, "type": "Goederen Laad- & Losbundel", "moederbundel": "Plassendale 1", "sporen": "Sporen 3 & 4 (via doodspoor 150/153)", "adres": "Zandvoordestraat / Oudenburgsesteenweg, 8400 Oostende", "toegang_weg": "Draaibrug over kanaal Brugge-Oostende", "beveiliging": "Omheining, poort, spoorwegdraaibrug bediend door personeel", "ppgi_ref": "PP-341 blz. 8, 26, 31", "lat": 51.211, "lng": 2.998, "aliases": ["Plassendale 1", "Industrieterrein Plassendale"]}'::jsonb),
  ('oostende_vorming', 'bediening', 'Oostende Vorming (117-118)', 51.222, 2.946, '["Oostende Vorming Spoor 117-118"]'::jsonb, '{"id": "oostende_vorming", "name": "Oostende Vorming (117-118)", "cluster": "oostende", "zone": "PP-341", "zone_name": "Oostende & Plassendale", "has_bi": false, "bi_version": null, "type": "Openbare Laad-/Lossporen", "moederbundel": "Bundel Vorming", "sporen": "Sporen 117 en 118", "adres": "Achterhaven Oostende (corridor Lijn 50A), 8400 Oostende", "toegang_weg": "Vuurtorenweg / Stapelhuisstraat", "beveiliging": "Overgedragen aan I-O.3, Siemenssleutelprocedure", "ppgi_ref": "PP-341 blz. 9, 26, 33", "lat": 51.222, "lng": 2.946, "aliases": ["Oostende Vorming Spoor 117-118"]}'::jsonb),
  ('whv_oostende', 'bediening', 'WHV Oostende & Bundel WET', 51.218, 2.955, '["WHV", "WET Oostende"]'::jsonb, '{"id": "whv_oostende", "name": "WHV Oostende & Bundel WET", "cluster": "oostende", "zone": "PP-341", "zone_name": "Oostende & Plassendale", "has_bi": false, "bi_version": null, "type": "Tractiewerkplaats & Onderhoud", "moederbundel": "Werkplaats Tractie", "sporen": "Spoor 253 en proefspoor 25kV", "adres": "Zandvoordestraat / Vuurtorenweg, 8400 Oostende", "toegang_weg": "Zandvoordestraat", "beveiliging": "Centrale aanvraag Blok 7, industriële seinpost", "ppgi_ref": "PP-341 blz. 9, 32-33, 66-72", "lat": 51.218, "lng": 2.955, "aliases": ["WHV", "WET Oostende"]}'::jsonb),
  ('alstom', 'bediening', 'SA Alstom (voorheen Bombardier)', 51.1915, 3.2215, '["Bombardier", "Bombardier Transportation Brugge", "Alstom Brugge"]'::jsonb, '{"id": "alstom", "name": "SA Alstom (voorheen Bombardier)", "cluster": "brugge", "zone": "FR/B", "zone_name": "Actiezone Brugge FR/B", "has_bi": true, "bi_version": "V1.3", "type": "Treinbouw & Fabrieksaansluiting", "moederbundel": "Station Brugge / Bundel U", "sporen": "Spoor 675 / 676", "adres": "Vaartdijkstraat 5, 8200 Brugge (Sint-Michiels)", "toegang_weg": "Vaartdijkstraat langs kanaal Gent-Brugge", "beveiliging": "Stuitklamp, Siemenssleutel met toelating Blok 7, sleepklaar Traxx BR186", "ppgi_ref": "PPGI_1_FR_B blz. 18, 20-21, 42", "lat": 51.1915, "lng": 3.2215, "aliases": ["Bombardier", "Bombardier Transportation Brugge", "Alstom Brugge"]}'::jsonb),
  ('lci_brugge', 'bediening', 'LCI Brugge (Logistiek Centrum Infrabel)', 51.196, 3.219, '["Logistiek Centrum Infrabel Brugge"]'::jsonb, '{"id": "lci_brugge", "name": "LCI Brugge (Logistiek Centrum Infrabel)", "cluster": "brugge", "zone": "FR/B", "zone_name": "Actiezone Brugge FR/B", "has_bi": false, "bi_version": null, "type": "Infrabel Werfbasis / Spoorbouw", "moederbundel": "Station Brugge", "sporen": "Spoor 3", "adres": "Hendrik Brugmansstraat, 8000 Brugge", "toegang_weg": "Hendrik Brugmansstraat nabij station Brugge", "beveiliging": "Stuitklamp met Siemenssleutel", "ppgi_ref": "PPGI_1_FR_B blz. 18, 21", "lat": 51.196, "lng": 3.219, "aliases": ["Logistiek Centrum Infrabel Brugge"]}'::jsonb),
  ('otwd_brugge', 'bediening', 'OTWD Brugge (Werkplaats Infrabel)', 51.188, 3.224, '["Onderhoudswerkplaats Infrabel Brugge"]'::jsonb, '{"id": "otwd_brugge", "name": "OTWD Brugge (Werkplaats Infrabel)", "cluster": "brugge", "zone": "FR/B", "zone_name": "Actiezone Brugge FR/B", "has_bi": false, "bi_version": null, "type": "Werkplaatsdomein Infrabel", "moederbundel": "Station Brugge", "sporen": "Spoor 638", "adres": "Ten Briele / Kuringenstraat, 8200 Brugge (Sint-Michiels)", "toegang_weg": "Ten Briele", "beveiliging": "Handbediende wissels door bediende IG", "ppgi_ref": "PPGI_1_FR_B blz. 21, 42", "lat": 51.188, "lng": 3.224, "aliases": ["Onderhoudswerkplaats Infrabel Brugge"]}'::jsonb),
  ('lci_lichtervelde', 'bediening', 'LCI Lichtervelde', 51.0295, 3.1435, '["Logistiek Centrum Infrabel Lichtervelde"]'::jsonb, '{"id": "lci_lichtervelde", "name": "LCI Lichtervelde", "cluster": "centraal", "zone": "FR/B", "zone_name": "Actiezone Brugge FR/B", "has_bi": false, "bi_version": null, "type": "Infrabel Spoorbouw & Knooppunt", "moederbundel": "Knooppunt L66 / L73", "sporen": "Bundel LCI Lichtervelde", "adres": "Statiestraat / Spoorweglaan, 8810 Lichtervelde", "toegang_weg": "Statiestraat", "beveiliging": "Lokale seininrichting", "ppgi_ref": "PPGI_1_FR_B blz. 26", "lat": 51.0295, "lng": 3.1435, "aliases": ["Logistiek Centrum Infrabel Lichtervelde"]}'::jsonb),
  ('bundel_roeselare', 'bediening', 'Bundel Roeselare', 50.946, 3.131, '["Vormingsbundel Roeselare"]'::jsonb, '{"id": "bundel_roeselare", "name": "Bundel Roeselare", "cluster": "centraal", "zone": "FR/B", "zone_name": "Actiezone Brugge FR/B", "has_bi": false, "bi_version": null, "type": "Goederenbundel", "moederbundel": "Lijn 66", "sporen": "Bundelsporen Roeselare", "adres": "Beversesteenweg / Spoorweglaan, 8800 Roeselare", "toegang_weg": "Beversesteenweg", "beveiliging": "Lokale capaciteit Infrabel", "ppgi_ref": "PPGI_1_FR_B blz. 32", "lat": 50.946, "lng": 3.131, "aliases": ["Vormingsbundel Roeselare"]}'::jsonb),
  ('bundel_blankenberge', 'bediening', 'Bundel Blankenberge (Bundel M)', 51.3125, 3.134, '["Bundel M Blankenberge"]'::jsonb, '{"id": "bundel_blankenberge", "name": "Bundel Blankenberge (Bundel M)", "cluster": "kust", "zone": "FR/B", "zone_name": "Actiezone Brugge FR/B", "has_bi": false, "bi_version": null, "type": "Wijkbundel Goederen/Reizigers", "moederbundel": "Lijn 51", "sporen": "Sporen 811 t.e.m. 816 en 820", "adres": "Spoorleggerstraat / Kerkstraat, 8370 Blankenberge", "toegang_weg": "Spoorleggerstraat", "beveiliging": "Beseinde bundel", "ppgi_ref": "PPGI_1_FR_B blz. 29, 41", "lat": 51.3125, "lng": 3.134, "aliases": ["Bundel M Blankenberge"]}'::jsonb),
  ('bundel_depanne', 'bediening', 'Bundel De Panne', 51.0775, 2.6025, '["Vorming De Panne"]'::jsonb, '{"id": "bundel_depanne", "name": "Bundel De Panne", "cluster": "kust", "zone": "FR/B", "zone_name": "Actiezone Brugge FR/B", "has_bi": false, "bi_version": null, "type": "Uitwijk- en Vormingsbundel", "moederbundel": "Lijn 73", "sporen": "Bundelsporen De Panne", "adres": "Stationsplein 9, 8660 De Panne / Adinkerke", "toegang_weg": "Stationsplein", "beveiliging": "Lokale capaciteit Infrabel", "ppgi_ref": "PPGI_1_FR_B blz. 23, 40", "lat": 51.0775, "lng": 2.6025, "aliases": ["Vorming De Panne"]}'::jsonb),
  ('lci_kortrijk', 'bediening', 'LCI Kortrijk (Logistiek Centrum Infrabel)', 50.835, 3.272, '["Logistiek Centrum Infrabel Kortrijk"]'::jsonb, '{"id": "lci_kortrijk", "name": "LCI Kortrijk (Logistiek Centrum Infrabel)", "cluster": "kortrijk", "zone": "FR/D", "zone_name": "Actiezone Kortrijk FR/D", "has_bi": false, "bi_version": null, "type": "Infrabel Werfbasis / Spoorbouw", "moederbundel": "Station Kortrijk", "sporen": "Doodsporen 266 en 267", "adres": "Minister Liebaertlaan, 8500 Kortrijk", "toegang_weg": "Minister Liebaertlaan", "beveiliging": "Geslotteerde stuitklamp met sleutel 433, slotkast", "ppgi_ref": "PPGI_1_FR_D blz. 18, 20, 23", "lat": 50.835, "lng": 3.272, "aliases": ["Logistiek Centrum Infrabel Kortrijk"]}'::jsonb),
  ('io3_kortrijk', 'bediening', 'Aansluiting I-O.3 Kortrijk', 50.825, 3.268, '["I-O.3 Kortrijk"]'::jsonb, '{"id": "io3_kortrijk", "name": "Aansluiting I-O.3 Kortrijk", "cluster": "kortrijk", "zone": "FR/D", "zone_name": "Actiezone Kortrijk FR/D", "has_bi": false, "bi_version": null, "type": "Technische Spooraansluiting", "moederbundel": "Station Kortrijk", "sporen": "Doodspoor 363", "adres": "Luiksestraat / spoorcorridor, 8500 Kortrijk", "toegang_weg": "Luiksestraat", "beveiliging": "Geslotteerde stuitklamp met sleutel 441, slotkast Slot LCI", "ppgi_ref": "PPGI_1_FR_D blz. 18, 20, 24", "lat": 50.825, "lng": 3.268, "aliases": ["I-O.3 Kortrijk"]}'::jsonb),
  ('kortrijk_vorming', 'bediening', 'Kortrijk Goederen / Vorming', 50.823, 3.264, '["Kortrijk Goederen", "Kortrijk Bundels A-D"]'::jsonb, '{"id": "kortrijk_vorming", "name": "Kortrijk Goederen / Vorming", "cluster": "kortrijk", "zone": "FR/D", "zone_name": "Actiezone Kortrijk FR/D", "has_bi": false, "bi_version": null, "type": "Centrale Rangeer- & Vormingsbundel", "moederbundel": "Lijn 75", "sporen": "Bundels A (357-360), B (227-239), C (221-226), D (251-260)", "adres": "Luiksestraat / Zandstraat / Schaapsdreef, 8500 Kortrijk", "toegang_weg": "Zandstraat / Luiksestraat", "beveiliging": "Beseinde bundels, bundelplaatjes, EBP Blok 7", "ppgi_ref": "PPGI_1_FR_D blz. 16-17, 38-39", "lat": 50.823, "lng": 3.264, "aliases": ["Kortrijk Goederen", "Kortrijk Bundels A-D"]}'::jsonb),
  ('lauwe', 'bediening', 'Bundel Lauwe', 50.796, 3.189, '["Vormingsstation Lauwe"]'::jsonb, '{"id": "lauwe", "name": "Bundel Lauwe", "cluster": "kortrijk", "zone": "FR/D", "zone_name": "Actiezone Kortrijk FR/D", "has_bi": false, "bi_version": null, "type": "Wijkbundel Goederen", "moederbundel": "Lijn 75", "sporen": "Sporen bundel Lauwe", "adres": "Spoorwegstraat, 8930 Lauwe (Menen)", "toegang_weg": "Spoorwegstraat", "beveiliging": "Lokaal protocol Infrabel", "ppgi_ref": "PPGI_1_FR_D blz. 25-27", "lat": 50.796, "lng": 3.189, "aliases": ["Vormingsstation Lauwe"]}'::jsonb),
  ('poperinge', 'bediening', 'Poperinge Goederen', 50.854, 2.738, '["Poperinge Goederensporen"]'::jsonb, '{"id": "poperinge", "name": "Poperinge Goederen", "cluster": "zuidwest", "zone": "FR/D", "zone_name": "Actiezone Kortrijk FR/D", "has_bi": false, "bi_version": null, "type": "Eindpunt Goederensporen", "moederbundel": "Lijn 69", "sporen": "Sporen 4 (654) en 5 (655)", "adres": "Europalaan, 8970 Poperinge", "toegang_weg": "Europalaan", "beveiliging": "Stootblokken, enkelsporige lijn exploitatie", "ppgi_ref": "PPGI_1_FR_D blz. 30, 38", "lat": 50.854, "lng": 2.738, "aliases": ["Poperinge Goederensporen"]}'::jsonb),
  ('bundel_0', 'bundel', 'Bundel Ramskapelle', 51.3125, 3.2255, '[]'::jsonb, '{"name": "Bundel Ramskapelle", "lat": 51.3125, "lng": 3.2255, "info": "Sporen 881-897 (Zuidelijk Insteekdok)"}'::jsonb),
  ('bundel_1', 'bundel', 'Bundel Pelikaan', 51.292613, 3.228543, '[]'::jsonb, '{"name": "Bundel Pelikaan", "lat": 51.292613, "lng": 3.228543, "info": "Sporen 861-875 (Zuidelijk Insteekdok)"}'::jsonb),
  ('bundel_2', 'bundel', 'Bundel Zwankendamme', 51.306043, 3.191378, '[]'::jsonb, '{"name": "Bundel Zwankendamme", "lat": 51.306043, "lng": 3.191378, "info": "Sporen 101-110"}'::jsonb),
  ('bundel_3', 'bundel', 'Bundel Voorhaven-West', 51.340854, 3.176165, '[]'::jsonb, '{"name": "Bundel Voorhaven-West", "lat": 51.340854, "lng": 3.176165, "info": "Sporen 700-717"}'::jsonb),
  ('bundel_4', 'bundel', 'Zeebrugge Vorming (Bundel A)', 51.318798, 3.188095, '[]'::jsonb, '{"name": "Zeebrugge Vorming (Bundel A)", "lat": 51.318798, "lng": 3.188095, "info": "Sporen 521-524"}'::jsonb),
  ('bundel_5', 'bundel', 'Bundel CHZ Terminal', 51.332113, 3.186722, '[]'::jsonb, '{"name": "Bundel CHZ Terminal", "lat": 51.332113, "lng": 3.186722, "info": "Sporen 1-7 (Albert II Dok)"}'::jsonb),
  ('bundel_6', 'bundel', 'Oostende Vorming', 51.222, 2.946, '[]'::jsonb, '{"name": "Oostende Vorming", "lat": 51.222, "lng": 2.946, "info": "Achterhaven Oostende"}'::jsonb),
  ('bundel_7', 'bundel', 'Station Brugge / Bundel U', 51.194, 3.221, '[]'::jsonb, '{"name": "Station Brugge / Bundel U", "lat": 51.194, "lng": 3.221, "info": "Centrale as L50A/L66"}'::jsonb),
  ('bundel_8', 'bundel', 'Kortrijk Vorming', 50.823, 3.264, '[]'::jsonb, '{"name": "Kortrijk Vorming", "lat": 50.823, "lng": 3.264, "info": "Bundels A, B, C, D (L75)"}'::jsonb)
;

-- 5. Optionele trigger om updated_at altijd automatisch bij te werken
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_locations_timestamp ON public.locations;
CREATE TRIGGER set_locations_timestamp
BEFORE UPDATE ON public.locations
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();
